import type { Metadata } from "next";
import { Geist_Mono, Noto_Sans_JP, Schibsted_Grotesk } from "next/font/google";
import "./globals.css";

// UIトーン統一 v2: 欧文・数字 = Schibsted Grotesk / 和文 = Noto Sans JP。
// 等幅(ID・コード表示)は従来どおり Geist Mono を維持。
const appSans = Schibsted_Grotesk({
  variable: "--font-app-sans",
  subsets: ["latin"],
});

const appSansJp = Noto_Sans_JP({
  variable: "--font-app-sans-jp",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${appSans.variable} ${appSansJp.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
