import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";

// UI総点検 B-6: 全画面のタブ名が「Create Next App」のままだった。日本語の社内システム名に是正する。
// layout.tsx は next/font を読むため import 実行は避け、ソース文字列で確認する。
const src = readFileSync(path.resolve(process.cwd(), "src/app/layout.tsx"), "utf-8");

describe("root layout メタデータ(UI総点検 B-6)", () => {
  it("タブ名の既定は「物件管理システム」で、Create Next App ではない", () => {
    expect(src).toContain('default: "物件管理システム"');
    expect(src).toContain('template: "%s | 物件管理システム"');
    expect(src).not.toContain("Create Next App");
    expect(src).not.toContain("Generated by create next app");
  });

  it("html の lang は日本語(ja)", () => {
    expect(src).toContain('lang="ja"');
    expect(src).not.toContain('lang="en"');
  });
});
